### ISSUE TITLE
Can not upload large size > 2GB

### ISSUE THREAD

**Issue by zolaahihi** [mrdotb/facebook-api-video-upload#10]
Dear Team,

I can not upload file large 2GB, It seems it is over max buffer size?

`Unhandled rejection RangeError [ERR_INVALID_OPT_VALUE]: The value "2385986836" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:275:3)
    at Function.concat (buffer.js:460:23)
    at concat (/var/upfb/node/node_modules/stream-to-promise/index.js:26:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)`

How can I solve this problem? Thanks Team

**Comment by mrdotb** [comment]
Hello there is no team only me.

Well you can try to increase nodejs allowed memory ```node --max_old_space_size=4096 script.js```

Using stream I guess I could upload the video in chunk without loading the entire video in memory. But I don't have time to do this.

**Comment by zolaahihi** [comment]
Thanks @MRdotB. The same error. I will try to edit your code,

I have editted your code to support reupload when a chunk error. How can I push it :D

**Comment by mrdotb** [comment]
Good, you can fork the project and make a pull request.

**Comment by zolaahihi** [comment]
Thanks bro, I have made a pull request

**Comment by mrdotb** [comment]
Thanks for the contribution :+1: , I make some clean and upgrade the module.
