### ISSUE TITLE
When is the video ready?

### ISSUE THREAD

**Issue by Shrekie** [mrdotb/facebook-api-video-upload#12]
This wrapper does return successful when the video has been uploaded, however there is no way to see when the video has finished processing after upload. I did not expect it to help in this manner, as implementing this as suggested by Facebook involves registering web-hooks to your app and waiting for a callback from Facebook. However there seems to be a way to solve it without web-hooks, my idea revolves around the idea of checking the video-status field of the given video periodically to see if the status field equals "ready" signaling video being completely uploaded and processed.

https://developers.facebook.com/docs/graph-api/reference/video-status/

I will go about implementing this, but i really do wonder if anyone has any better ideas.

Anyway, great plugin makes video upload much less of a hassle.

Might update with my not so perfect solution to this, might decide to just go with the web-hook thing.

**Comment by Shrekie** [comment]
```
const options = {
	method: 'GET',
	uri: 'https://graph.facebook.com/v2.11/'+vres.video_id,
	qs: {
		access_token:req.user.accessToken,
		fields:'status'
	}
	};
	
waitUntil()
.interval(5000)
.times(10)
.condition(function(cb) {
	request(options)
		.then(fbRes => {
		const parsedRes = JSON.parse(fbRes).status;
		cb(parsedRes.video_status == 'ready'?true:false);
	});
})
.done(function(result) {
	//if(!result) timeout catch here
	res.json({shareLink});
});
```

Yeah looks something like this inside a successful fbUpload, since the graph call is lightweight the load is relatively low.

**Comment by mrdotb** [comment]
This is beyond the scope of this module but I'm glad you solved your issue.
