### ISSUE TITLE
Getting an error: (#100) No permission to publish the video

### ISSUE THREAD

**Issue by DaveLomber** [mrdotb/facebook-api-video-upload#16]
Hi there

I'm getting an "error: (#100) No permission to publish the video" when try to upload a video

I'm getting it on both - using your package and using Web JS SDK

I did everything what Facebook says, but still no luck(

explained in details it here
https://stackoverflow.com/questions/52651061/facebook-js-sdk-100-no-permission-to-publish-the-video-error

Could please check it, maybe you will have some idea..

Thank you

**Comment by mrdotb** [comment]
Hmm try to do it with curl.

**Comment by DaveLomber** [comment]
@mrdotb 
I had a long discussion on a Facebook devs group and realized that I can't upload a video to user's timeline via API, only to some Page using a page access token
So that's why it is  not working in my case 

As guys said, this is because of 1st April 2018 changes with Facebook policy
