### ISSUE TITLE
Uploading a video with a specific thumbnail

### ISSUE THREAD

**Issue by LexiBrush** [mrdotb/facebook-api-video-upload#17]
Currently using this node module to upload a video to facebook successfully, however we're struggling to see how we could go about setting a specific image as the video's thumbnail, any ideas?

**Comment by mrdotb** [comment]
I checked the Facebook documentation linked in the readme. There is a section called post video with a thumbnail. Endpoint looks different. I'm on holiday atm so I can't help you more. If you find a solution please fork and submit a PR😃

**Comment by mrdotb** [comment]
@LexiBrush Did you find something ?

**Comment by LexiBrush** [comment]
I must admit I haven't even looked into it yet, I do plan on investigating it later this week though.

**Comment by mrdotb** [comment]
I have added support for thumb and all the other fields in the api check the updated README.
Don't forget to :star:  :smile:
