### ISSUE TITLE
How to config private video

### ISSUE THREAD

**Issue by EAADdszLrcgUBAH3p6QZARzvA3Os7NISc6UZ** [mrdotb/facebook-api-video-upload#19]
I want to configure public video blocking and set secret mode without knowing how to configure it. The config always returns an error. Can you help me with this .. thanks

when add 

 The first argument must be one of type string or Buffer. Received type boolean
```
    const args = {
        token: "TOKEN", // with the permission to upload
        id: "408178802639894", //The id represent {page_id || user_id || event_id || group_id}
        stream: fs.createReadStream(pathVideo), //path to the video,
        title: _name,
        description: _name,
        no_story: true,
        published:false
        // if you want the default thumb from the video just remove the field
        // you can add any extra fields from the api https://developers.facebook.com/docs/graph-api/reference/page/videos/#Creating
        // all keys except token, id, stream are passed to the final request
      };

```

ERROR==>

```
_http_outgoing.js:607
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type boolean
```

**Comment by mrdotb** [comment]
I don't understand what you try to achieve. Are you referring to the field ?
privacyPrivacy | Privacy setting for the video.
Check the extra fields documentation https://developers.facebook.com/docs/graph-api/reference/video

**Comment by holygrolli** [comment]
I had the same problem and solved it with putting the Booleans into quotes so they will be handled as Strings.
