### ISSUE TITLE
streamToPromise(...).then(...).spread is not a function

### ISSUE THREAD

**Issue by gregory-h** [mrdotb/facebook-api-video-upload#20]
Using this in a production app and have recently started seeing this error

TypeError: streamToPromise(...).then(...).spread is not a function
1
at facebookApiVideoUpload (/var/app/current/node_modules/facebook-api-video-upload/index.js line 96 col 4)

**Comment by mrdotb** [comment]
There is some weird behavior with bluebird Promise I got the same error when I add some features.
I remove bluebird deps and use es6 instead.
Can you try to just upgrade my package to version 2 ?

**Comment by gregory-h** [comment]
Ah yes that seems to solve it, thanks
