### ISSUE TITLE
Graph API version should be parameterized

### ISSUE THREAD

**Issue by sagar7993** [mrdotb/facebook-api-video-upload#22]
Graph API version is hardcoded in the index.js file. It would be great if you could expose that as an argument to the function so that I can use the latest version of Graph API, i.e `v7.0`

**Comment by mrdotb** [comment]
I don't agree with you. 
How can you guaranty the module will still work with newer version of the graph API ?

**Comment by sagar7993** [comment]
I don't expect you to guarantee that it will work with every new version of Graph API. But it is certainly a good idea to allow developers to take advantage of the new versions of the Graph API. Not having any ability to use the desired version of Graph API is not a good approach, in my opinion.

**Comment by mrdotb** [comment]
Suppose we add an optional parameter to specify the version of the Graph API default will be `3.2`.
Maybe it  work if put a version > 3 .
Maybe it will break.
They have a versioned API to be able to make breaking change without impacting the one who rely on the old behavior.
