### ISSUE TITLE
Type error when specifying if published or not

### ISSUE THREAD

**Issue by feddynventor** [mrdotb/facebook-api-video-upload#24]
When specifying in the arguments if the post is published or not I get this error
`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type boolean`
How to specify a true or false preference?

**Comment by mrdotb** [comment]
I check the fb doc it should work. Can you show the code who trigger the error ?

**Comment by feddynventor** [comment]
`const args = {
    token: token,
    id: page_id,
    stream: fs.createReadStream(UPLOAD_DIR+filename),
    title: ..............,
    description: ..............,
    published: false,
    scheduled_publish_time: pub
  };`

If I try putting a String like "false" the upload hangs. Meanwhile the Boolean type is not accepted.

**Comment by mrdotb** [comment]
Can you try with a small video and the boolean in a string ?
Did you try and succeed to upload video without this field ?

**Comment by feddynventor** [comment]
Without the `published` parameter if I leave the `scheduled_publish_time` it says `Facebook Error 100: You cannot specify a scheduled publish time on a published post`. If I put basic parameters the argument set works and the file is uploaded in few seconds.

**Comment by mrdotb** [comment]
Did you find a way to upload with `scheduled_publish_time` ?

**Comment by feddynventor** [comment]
Not yet, this is a secondary task.

**Comment by mrdotb** [comment]
Ok I don't have that much time right now if you find a way to make it work keep me updated.

**Comment by mrdotb** [comment]
If you find a solution for it feel free to post it here.

**Comment by feddynventor** [comment]
Every parameter must be in string.
A configuration like this works:
```
published: "false",
scheduled_publish_time: "1624967710"
```
Plus `scheduled_publish_time` must represent an epoch at least 10 minutes late than the publish time, but in this case the error is submitted from the Facebook API as a regular message.
