### ISSUE TITLE
[Feature Request] Upload Progress

### ISSUE THREAD

**Issue by pundoo** [mrdotb/facebook-api-video-upload#31]
Showing percent/amount uploaded, upload speed etc. would be useful.

**Comment by mrdotb** [comment]
It's doable but I don't have time to work on that right know. PR is welcome

**Comment by pundoo** [comment]
Same here! Will do when I got the time.

Also, bit off-topic.. Its not working with large files. `streamToPromise` reading the entire file into memory, and the process gets terminated due to out-of-memory. You should read the file in chunks as well :)

**Comment by mrdotb** [comment]
I guess something with [fs.read](https://nodejs.org/docs/latest-v15.x/api/fs.html#fs_filehandle_read_buffer_offset_length_position) and just read a part of the buffer will be better. But I don't use this library anymore just maintain it. So I will not invest too much time in it.
