### ISSUE TITLE
v1.2.0 exits with an error

### ISSUE THREAD

**Issue by kedadi42** [mrdotb/facebook-api-video-upload#4]
I'm running the sample code for video upload with my own credentials, using the latest version (v1.2.0) but it exits with the following error:

> node upload.js 
/Users/kr/Documents/node_modules/facebook-api-video-upload/index.js:36
	return rp(options).then(res => ({ ...res, id: video_id }));
	                                  ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kr/Documents/biber/upload.js:2:18)
    at Module._compile (module.js:571:32)

With version v1.1.1 it works just fine (but it doesn't return the video id after upload).

The following is my environment:
-OS: macos sierra
-node: v7.2.1
-npm: v3.10.9

**Comment by mrdotb** [comment]
The spread operator added on last PR is not working without babel. I remove it for now.

**Comment by kedadi42** [comment]
Now with v1.2.1 it reports that it uploaded the video (and it took a few seconds uploading), but in reality looks like it didn't (it's not showing up).

I downgraded to v1.1.1 and the same code worked just fine.

**Comment by kedadi42** [comment]
and it also returns a video id, but which is not accessible...

also Facebook Video Library shows that a video upload is being attempted, it stays on "Processing" indefinitely

**Comment by mrdotb** [comment]
I'm going back to 1.1 and add support to video_id

**Comment by kedadi42** [comment]
Great.

I've never worked with promises before and it seems quite challenging to me, can't seem to be able to grasp it.

I installed v1.1.1 myself and did a dirty hack to output the video_id for my needs, but by no means it can be part of the library... so looking forward for your fix.

Thanks

**Comment by mrdotb** [comment]
I rollback and add support to video_id. I test it with several video upload and it's working. Update is published on the npm package.
Thanks for your feedback.

**Comment by kedadi42** [comment]
Just tried it and it works like a charm

Very much appreciated :)
