### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by majorcyto** [mrdotb/facebook-api-video-upload#7]
Hi,

I installed the package with npm.. but even with usage in the readme I am still not sure how to actually "use" it. Is there any way you can expand on the details any for usage?

**Comment by mrdotb** [comment]
Hello,

I don't think I can do better it's very simple to use. Just copy paste the README usage with your fb stuff and path to the video you want to upload.
If you don't know how the facebook api work there is a link in the README.
