### ISSUE TITLE
Is there anyway to get uploaded percent?

### ISSUE THREAD

**Issue by kieusonlam** [mrdotb/facebook-api-video-upload#8]
Hi,

I have a question, is there anyway to get uploaded percent? Thanks.

**Comment by mrdotb** [comment]
Hello, it was not designed to do this. Since I don't use stream a big refactoring is needed to do this

**Comment by kieusonlam** [comment]
Thanks for your answer. I close this question for now 👍 Have a good day!

**Comment by usamamashkoor** [comment]
@kieusonlam did you find any solution...?

**Comment by kieusonlam** [comment]
@usamamashkoor no, I couldn't find a solution for this.

**Comment by usamamashkoor** [comment]
Thanks for letting me know @kieusonlam
