### ISSUE TITLE
is their a way we can implement this in the browser with progress bar using javaScript...?

### ISSUE THREAD

**Issue by usamamashkoor** [mrdotb/facebook-api-video-upload#9]
is their a way we can implement this in the browser with progress bar using javaScript...?

**Comment by mrdotb** [comment]
Doing the upload on client-side only is probably possible but it's not the goal of the module. see this for the progress bar. https://github.com/MRdotB/facebook-api-video-upload/issues/8

**Comment by usamamashkoor** [comment]
Thanks for the reply can you suggest a approach how i can achieve this using client side as you are JavaScript  expert.

Thanks again.

**Comment by mrdotb** [comment]
Hmm I will try to get the blob of the video using the html5 file api then transform it to a buffer with https://www.npmjs.com/package/blob-to-buffer and doing some minor change on my module and it should work.

Good luck I close this issue.

**Comment by usamamashkoor** [comment]
Thanks @MRdotB
